# Generated by Django 5.2.16 on 2026-07-19 05:03

from django.db import migrations
from django.db.models import Q


def purge_assignment_traces(apps, schema_editor):
    AssignmentSubmission = apps.get_model('portal', 'AssignmentSubmission')
    EmailNotification = apps.get_model('portal', 'EmailNotification')
    ActivityLog = apps.get_model('portal', 'ActivityLog')

    for submission in AssignmentSubmission.objects.exclude(file='').iterator():
        if submission.file:
            submission.file.delete(save=False)

    EmailNotification.objects.filter(event_type__istartswith='ASSIGNMENT').delete()
    ActivityLog.objects.filter(
        Q(entity__icontains='assignment') | Q(details__icontains='assignment')
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_course_thumbnail'),
    ]

    operations = [
        migrations.RunPython(purge_assignment_traces, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
