# Generated by Django 5.1.7 on 2026-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='recommended_courses',
            field=models.JSONField(default=list),
        ),
    ]
