"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { Compass, RefreshCw, Send, Sparkles } from "lucide-react";
import { useAuth } from "@/components/auth-provider";
import { useFeedbackDialog } from "@/components/feedback-dialog-provider";
import { Empty, ErrorMessage, Loading, LoadingModal, PageHeader } from "@/components/ui";
import { useApiData } from "@/hooks/use-api-data";
import { api, jsonBody, unwrap } from "@/lib/api";
import type { Course, Quiz } from "@/lib/types";
import { AdvisorRecommendationCards } from "@/components/advisor/recommendation-cards";
import { studentAdvisorStatusLabel } from "@/components/advisor/status";
import type { AdvisorAttempt as Attempt } from "@/components/advisor/types";

type Field = { id: number; name: string; description: string; is_active: boolean; skills: { id: number; name: string }[] };
export function LearningPathPage() {
  const { user } = useAuth();
  return user?.role === "ADMIN" ? <AdminAdvisor /> : <StudentAdvisor />;
}

function StudentAdvisor() {
  const fields = useApiData<Field[] | { results: Field[] }>("/advisor/fields/");
  const quizzes = useApiData<Quiz[] | { results: Quiz[] }>("/advisor/quizzes/");
  const attempts = useApiData<Attempt[] | { results: Attempt[] }>("/advisor/attempts/");
  const [mode, setMode] = useState<"SKILL_DISCOVERY" | "SKILL_DEVELOPMENT" | null>(null);
  const [field, setField] = useState<number | null>(null);
  if (fields.loading || quizzes.loading || attempts.loading) return <Loading variant="dashboard" />;
  if (fields.error || quizzes.error || attempts.error) return <ErrorMessage message={fields.error || quizzes.error || attempts.error || "Unable to load Advisor"} />;
  const allQuizzes = unwrap(quizzes.data || []);
  const prior = new Set(unwrap(attempts.data || []).map(a => a.quiz_title));
  const visible = allQuizzes.filter(q => q.quiz_type === mode && (mode !== "SKILL_DEVELOPMENT" || q.target_field === field));
  return <div className="space-y-6">
    <PageHeader title="AI Learning Path Advisor" description="Discover your strongest skill or develop a field you choose." />
    <div className="grid gap-4 md:grid-cols-2">
      <button className={`advisor-option-card panel p-6 text-left transition-all duration-200 hover:-translate-y-1 hover:scale-[1.01] hover:border-[var(--primary)] hover:bg-[color-mix(in_srgb,var(--primary)_6%,var(--panel))] hover:shadow-xl ${mode === "SKILL_DISCOVERY" ? "ring-2 ring-[var(--primary)]" : ""}`} onClick={() => { setMode("SKILL_DISCOVERY"); setField(null); }}>
        <Compass className="text-[var(--primary)]" /><h2 className="mt-3 text-xl font-bold">Skill Discovery</h2><p className="muted mt-2">Take the existing Initial Assessment, then receive strongest-skill analysis and the best course recommendation.</p>
      </button>
      <button className={`advisor-option-card panel p-6 text-left transition-all duration-200 hover:-translate-y-1 hover:scale-[1.01] hover:border-[var(--primary)] hover:bg-[color-mix(in_srgb,var(--primary)_6%,var(--panel))] hover:shadow-xl ${mode === "SKILL_DEVELOPMENT" ? "ring-2 ring-[var(--primary)]" : ""}`} onClick={() => setMode("SKILL_DEVELOPMENT")}>
        <Sparkles className="text-[var(--primary)]" /><h2 className="mt-3 text-xl font-bold">Skill Development</h2><p className="muted mt-2">Choose a field, identify your level and gaps, and receive a matching course recommendation.</p>
      </button>
    </div>
    {mode === "SKILL_DEVELOPMENT" && <section className="panel p-5"><h2 className="font-bold">Choose a field</h2><div className="mt-4 flex flex-wrap gap-2">{unwrap(fields.data || []).map(item => <button className={field === item.id ? "btn btn-primary" : "btn btn-secondary"} key={item.id} onClick={() => setField(item.id)}>{item.name}</button>)}</div></section>}
    {mode && (mode === "SKILL_DISCOVERY" || field) && <section className="space-y-3"><h2 className="text-xl font-bold">Available assessment</h2>{visible.length ? visible.map(q => <article className="panel flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between" key={q.id}><div><h3 className="font-bold">{q.title}</h3><p className="muted text-sm">{q.description}</p></div>{prior.has(q.title) ? <span className="badge">Already attempted</span> : <Link className="btn btn-primary" href={`/quizzes/${q.id}`}>Take quiz</Link>}</article>) : <Empty message="An admin has not published an assessment for this option yet." />}</section>}
    <section className="space-y-3"><h2 className="text-xl font-bold">Your Advisor results</h2>{unwrap(attempts.data || []).length ? unwrap(attempts.data || []).map(a => <article className="panel p-5" key={a.id}><div className="flex flex-wrap items-center gap-2"><strong>{a.quiz_title}</strong><span className="badge">{studentAdvisorStatusLabel(a.analysis_status)}</span></div>{a.analysis ? <div className="mt-4 space-y-3"><p>{a.analysis.summary}</p>{a.analysis.strongest_field_name && <p><strong>Strongest field:</strong> {a.analysis.strongest_field_name}</p>}{a.analysis.level && <p><strong>Level:</strong> {a.analysis.level}</p>}{a.analysis.gaps.length > 0 && <p><strong>Gaps:</strong> {a.analysis.gaps.join(", ")}</p>}<AdvisorRecommendationCards recommendations={a.analysis.recommendations} /><Link className="btn btn-secondary" href={`/quizzes/${a.quiz}`}>View full result</Link></div> : <p className="muted mt-3 text-sm">{a.analysis_status === "ANALYSIS_FAILED" ? "Your answers are safe. An administrator will retry the AI analysis." : "Your result will appear after administrator review and publication."}</p>}</article>) : <Empty message="No attempts yet. Choose one of the Advisor options above." />}</section>
  </div>;
}

function AdminAdvisor() {
  const { notify } = useFeedbackDialog();
  const fields = useApiData<Field[] | { results: Field[] }>("/advisor/fields/");
  const attempts = useApiData<Attempt[] | { results: Attempt[] }>("/advisor/attempts/");
  const courses = useApiData<Course[] | { results: Course[] }>("/courses/");
  const [busy, setBusy] = useState("");
  const rows = useMemo(() => unwrap(attempts.data || []), [attempts.data]);
  async function createField(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { setBusy("Creating field…"); await api("/advisor/fields/", { method: "POST", body: jsonBody({ name: data.get("name"), slug: String(data.get("name") || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), description: data.get("description"), is_active: true, order: 0 }) }); form.reset(); await fields.reload(); } catch (e) { void notify(e instanceof Error ? e.message : "Unable to create field", { tone: "error" }); } finally { setBusy(""); } }
  async function createSkill(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { setBusy("Creating skill…"); await api("/advisor/skills/", { method: "POST", body: jsonBody({ field: Number(data.get("field")), name: data.get("name"), description: "", is_active: true }) }); form.reset(); await fields.reload(); } catch (e) { void notify(e instanceof Error ? e.message : "Unable to create skill", { tone: "error" }); } finally { setBusy(""); } }
  async function mapCourse(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { setBusy("Mapping course skill…"); await api("/advisor/course-skills/", { method: "POST", body: jsonBody({ course: Number(data.get("course")), skill: Number(data.get("skill")), coverage: 100 }) }); form.reset(); void notify("Course skill mapped.", { tone: "success" }); } catch (e) { void notify(e instanceof Error ? e.message : "Unable to map course", { tone: "error" }); } finally { setBusy(""); } }
  async function act(id: number, action: "analyze" | "publish") { try { setBusy(action === "analyze" ? "Asking AI to analyze the complete assessment…" : "Publishing result…"); await api(`/advisor/attempts/${id}/${action}/`, { method: "POST", body: "{}" }); await attempts.reload(); } catch (e) { void notify(e instanceof Error ? e.message : "Action failed", { tone: "error" }); } finally { setBusy(""); } }
  async function saveDraft(event: FormEvent<HTMLFormElement>, id: number) { event.preventDefault(); const data = new FormData(event.currentTarget); const course = Number(data.get("course") || 0); try { setBusy("Saving reviewed draft…"); await api(`/advisor/attempts/${id}/draft/`, { method: "PATCH", body: jsonBody({ summary: data.get("summary"), strongest_field: Number(data.get("strongest_field") || 0) || null, strengths: String(data.get("strengths") || "").split("\n").map(v => v.trim()).filter(Boolean), gaps: String(data.get("gaps") || "").split("\n").map(v => v.trim()).filter(Boolean), recommendations: course ? [{ course, match_type: data.get("match_type"), reason: data.get("reason") }] : [] }) }); await attempts.reload(); } catch (e) { void notify(e instanceof Error ? e.message : "Unable to save draft", { tone: "error" }); } finally { setBusy(""); } }
  if (fields.loading || attempts.loading || courses.loading) return <Loading variant="dashboard" />;
  return <div className="space-y-6"><LoadingModal open={Boolean(busy)} title="AI Learning Path Advisor" message={busy} /><PageHeader title="AI Learning Path Advisor" description="Configure fields and review student assessments before publishing results." />
    <section className="panel p-5"><h2 className="text-lg font-bold">Fields, skills, and course coverage</h2><form className="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto]" onSubmit={createField}><input className="field" name="name" placeholder="Field name" required /><input className="field" name="description" placeholder="Description" /><button className="btn btn-primary">Add field</button></form><form className="mt-3 grid gap-3 md:grid-cols-[1fr_2fr_auto]" onSubmit={createSkill}><select className="field" name="field" required defaultValue=""><option value="" disabled>Choose field</option>{unwrap(fields.data || []).map(f => <option value={f.id} key={f.id}>{f.name}</option>)}</select><input className="field" name="name" placeholder="Skill name" required /><button className="btn btn-secondary">Add skill</button></form><form className="mt-3 grid gap-3 md:grid-cols-[1fr_1fr_auto]" onSubmit={mapCourse}><select className="field" name="course" required defaultValue=""><option value="" disabled>Choose course</option>{unwrap(courses.data || []).map(c => <option value={c.id} key={c.id}>{c.title}</option>)}</select><select className="field" name="skill" required defaultValue=""><option value="" disabled>Choose covered skill</option>{unwrap(fields.data || []).flatMap(f => f.skills.map(s => <option value={s.id} key={s.id}>{f.name} — {s.name}</option>))}</select><button className="btn btn-secondary">Map course</button></form><div className="mt-4 flex flex-wrap gap-2">{unwrap(fields.data || []).map(f => <span className="badge" key={f.id}>{f.name}: {f.skills.map(s => s.name).join(", ") || "no skills"}</span>)}</div></section>
    <section className="space-y-3"><h2 className="text-xl font-bold">Assessment review queue</h2>{rows.length ? rows.map(a => <article className="panel p-5" key={a.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><strong>{a.quiz_title}</strong><div className="mt-2 flex gap-2"><span className="badge">{a.quiz_type.replaceAll("_", " ")}</span><span className="badge">{a.analysis_status.replaceAll("_", " ")}</span></div>{a.analysis_error && <p className="error mt-2">{a.analysis_error}</p>}</div><div className="flex gap-2">{["SUBMITTED", "ANALYSIS_FAILED", "DRAFT_READY"].includes(a.analysis_status) && <button className="btn btn-secondary" onClick={() => void act(a.id, "analyze")}><RefreshCw size={15} />{a.analysis_status === "DRAFT_READY" ? "Rerun AI" : "Analyze with AI"}</button>}{a.analysis_status === "DRAFT_READY" && <button className="btn btn-primary" onClick={() => void act(a.id, "publish")}><Send size={15} />Publish</button>}</div></div>{a.analysis && (a.analysis_status === "DRAFT_READY" ? <form className="mt-4 grid gap-3 rounded-lg border border-[var(--border)] p-4" onSubmit={event => void saveDraft(event, a.id)}><label className="font-semibold text-sm">Summary<textarea className="field mt-1" name="summary" defaultValue={a.analysis.summary} rows={3} /></label><div className="grid gap-3 md:grid-cols-2"><label className="font-semibold text-sm">Strengths<textarea className="field mt-1" name="strengths" defaultValue={a.analysis.strengths.join("\n")} rows={4} /></label><label className="font-semibold text-sm">Gaps<textarea className="field mt-1" name="gaps" defaultValue={a.analysis.gaps.join("\n")} rows={4} /></label></div><p className="text-sm"><strong>AI strongest field:</strong> {a.analysis.strongest_field_name || "Needs admin correction"} · <strong>Level:</strong> {a.analysis.level || "—"}</p><button className="btn btn-secondary justify-self-start">Save reviewed draft</button></form> : <div className="mt-4 rounded-lg border border-[var(--border)] p-4"><p>{a.analysis.summary}</p>{a.analysis.strongest_field_name && <p className="mt-2"><strong>Strongest:</strong> {a.analysis.strongest_field_name}</p>}<p className="mt-2"><strong>Level:</strong> {a.analysis.level || "—"}</p></div>)}</article>) : <Empty message="The review queue is empty. Student Advisor attempts will appear here." />}</section>
  </div>;
}
