"use client";
import { FormEvent } from "react";
import { api, jsonBody, unwrap } from "@/lib/api";
import { useApiData } from "@/hooks/use-api-data";
import { useAuth } from "@/components/auth-provider";
import { Empty, ErrorMessage, Loading, PageHeader } from "@/components/ui";
import type { Course } from "@/lib/types";
type Payment={id:number;student_name:string;course_title:string;method:string;transaction_id:string;amount:string;status:string;admin_note:string};
type Method={method:string;display_name:string;account_details:string;account_holder:string;instructions:string};
export function PaymentsPage(){
 const {user}=useAuth(); const list=useApiData<Payment[]|{results:Payment[]}>("/payments/"); const methods=useApiData<Method[]|{results:Method[]}>("/payment-methods/"); const courses=useApiData<Course[]|{results:Course[]}>(user?.role==="STUDENT"?"/courses/":null);
 async function submitPayment(e:FormEvent<HTMLFormElement>){e.preventDefault();await api("/payments/",{method:"POST",body:new FormData(e.currentTarget)});e.currentTarget.reset();await list.reload()}
 async function addMethod(e:FormEvent<HTMLFormElement>){e.preventDefault();await api("/payment-methods/",{method:"POST",body:jsonBody(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();await methods.reload()}
 async function review(id:number,decision:"APPROVED"|"REJECTED"){const admin_note=decision==="REJECTED"?(window.prompt("Rejection reason")||""):"";if(decision==="REJECTED"&&!admin_note)return;await api(`/payments/${id}/review/`,{method:"POST",body:jsonBody({decision,admin_note})});await list.reload()}
 if(list.loading||methods.loading)return <Loading/>;
 return <div className="space-y-6"><PageHeader title="Payment Management" description="Manual bKash, Nagad, and Bank Pay review."/>{list.error&&<ErrorMessage message={list.error}/>} 
 {user?.role==="ADMIN"&&<><form className="panel p-5 grid gap-3 md:grid-cols-2" onSubmit={addMethod}><select className="field" name="method" required><option value="">Configure payment method</option><option value="BKASH">bKash</option><option value="NAGAD">Nagad</option><option value="BANK_PAY">Bank Pay</option></select><input className="field" name="display_name" placeholder="Display name" required/><textarea className="field" name="account_details" placeholder="Account number or bank details" required/><input className="field" name="account_holder" placeholder="Account holder"/><textarea className="field" name="instructions" placeholder="Student instructions"/><button className="btn btn-primary">Add method</button></form><div className="grid-cards">{unwrap(methods.data||[]).map(m=><article className="panel p-4" key={m.method}><strong>{m.display_name}</strong><p>{m.account_details}</p><p className="muted text-sm">{m.account_holder}</p></article>)}</div></>}
 {user?.role==="STUDENT"&&<><div className="grid-cards">{unwrap(methods.data||[]).map(m=><article className="panel p-4" key={m.method}><h2 className="font-bold">{m.display_name}</h2><p>{m.account_details}</p><p className="muted text-sm">{m.account_holder}</p><p className="muted text-sm">{m.instructions}</p></article>)}</div><form className="panel p-5 grid gap-3 md:grid-cols-2" onSubmit={submitPayment}><select className="field" name="course" required><option value="">Select paid course</option>{unwrap(courses.data||[]).filter(c=>c.course_type==="PAID"&&!c.is_enrolled).map(c=><option value={c.id} key={c.id}>{c.title} - BDT {c.price}</option>)}</select><select className="field" name="method" required><option value="">Payment method</option>{unwrap(methods.data||[]).map(m=><option value={m.method} key={m.method}>{m.display_name}</option>)}</select><input className="field" name="sender_details" placeholder="Sender account / bank details" required/><input className="field" name="transaction_id" placeholder="Transaction / reference ID" required/><input className="field" name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required/><input className="field" name="payment_date" type="date" required/><input className="field" name="proof" type="file" accept="image/jpeg,image/png,image/webp" required/><button className="btn btn-primary">Submit payment</button></form></>}
 <section className="space-y-3"><h2 className="text-xl font-bold">Payment records</h2>{!unwrap(list.data||[]).length?<Empty message="No payment records."/>:unwrap(list.data||[]).map(p=><article className="panel p-4 flex flex-wrap items-center justify-between gap-3" key={p.id}><div><strong>{p.course_title}</strong><p className="muted text-sm">{p.student_name} · {p.method} · {p.transaction_id} · BDT {p.amount}</p>{p.admin_note&&<p className="text-sm">{p.admin_note}</p>}</div><div className="flex gap-2"><span className="badge">{p.status}</span>{user?.role==="ADMIN"&&p.status==="PENDING"&&<><button className="btn btn-primary" onClick={()=>void review(p.id,"APPROVED")}>Approve</button><button className="btn btn-danger" onClick={()=>void review(p.id,"REJECTED")}>Reject</button></>}</div></article>)}</section>
 </div>
}
